/**
 * Shared model types for the health check API.
 *
 * Keep these types aligned with the backend `/health` response.
 */

export type HealthOverallStatus = 'UP' | 'DOWN';

export type DbStatus = 'CONNECTED' | 'DISCONNECTED' | 'UP' | 'DOWN' | 'OK' | 'ERROR' | 'UNKNOWN';

/**
 * The backend `/health` endpoint response structure.
 * Note: some fields may vary slightly depending on backend implementation, so optional
 * fields are included to keep the frontend resilient.
 */
export interface HealthResponse {
  /** Overall backend health status (e.g. UP/DOWN). */
  status: HealthOverallStatus | string;

  /** Uptime of the backend, in seconds (if provided by backend). */
  uptimeSeconds?: number;

  /** Uptime of the backend, in milliseconds (if provided by backend). */
  uptimeMs?: number;

  /** ISO timestamp generated by the backend (if provided by backend). */
  timestamp?: string;

  /** Database status information (if backend provides it). */
  db?: {
    status?: DbStatus | string;
    details?: string;
    message?: string;
  };

  /** Alternate DB fields if backend uses a different shape. */
  dbStatus?: DbStatus | string;
  dbDetails?: string;
  details?: string;
}
